### ISSUE TITLE
Make `braced!` macros and similar use question marks instead of returns for errors

### ISSUE THREAD

**Issue by AZMCode** [dtolnay/syn#1046]
I've been coding with the nightly `try {}` blocks feature, and have been disappointed to find that the `braced!`, `parenthesized!`, etc macros return on error instead of using the question mark, which means that my whole function returns unexpectedly instead of being caught by the try block.

As an example, the current `braced!` macro, which currently looks like this:
```
macro_rules! braced {
    ($content:ident in $cursor:expr) => {
        match $crate::group::parse_braces(&$cursor) {
            $crate::__private::Ok(braces) => {
                $content = braces.content;
                braces.token
            }
            $crate::__private::Err(error) => {
                return $crate::__private::Err(error);
            }
        }
    };
}
```

Could instead look like this:
```
macro_rules! braced {
    ($content:ident in $cursor:expr) => {
        match $crate::group::parse_braces(&$cursor) {
            $crate::__private::Ok(braces) => {
                $content = braces.content;
                braces.token
            }
            $crate::__private::Err(error) => {
                $crate::__private::Err(error)?;
            }
        }
    };
}
```

**Comment by dtolnay** [comment]
I agree we eventually want `?` in the expansion but it's blocked on https://github.com/rust-lang/rust/issues/84277. The unstable `Try` implementation on `Result` is not usable for our purposes because it bundles an extra `From` conversion which makes return types ambiguous.

For example the following code works with `return` but not `?` in the macro.

```rust
use syn::parse::ParseStream;

fn main() {
    let _ = |input: ParseStream| {
        let content;
        braced!(content in input);
        let ident = content.parse::<syn::Ident>()?;
        Ok(ident)
    };
}
```

```console
error[E0282]: type annotations needed for the closure `fn(&ParseBuffer<'_>) -> Result<syn::Ident, _>`
 --> src/main.rs:8:9
  |
8 |         Ok(ident)
  |         ^^ cannot infer type for type parameter `E` declared on the enum `Result`
  |
help: give this closure an explicit return type without `_` placeholders
  |
4 |     let _ = |input: ParseStream| -> Result<syn::Ident, _> {
  |                                  ++++++++++++++++++++++++
```

**Comment by waynr** [comment]
:wave: Howdy!

I came across this issue after spending some time trying to wrap my head around just how I should go about parsing a non-standard grouping of tokens. I would probably be fine using the `braced!` and `bracketed!` macros but for the problem described here of the expanded code returning instead of allowing me to handle the lack of bracketed content. To illustrate why this makes things somewhat difficult for me here is the example syntax I am targeting with my Parser implementation:

```
#[cfg(test)]
mod tests {
    use quote::quote;

    use super::*;
    #[test]
    fn valid_syntax() {
        parse(
            quote!(
                ModLayer[Active]: {
                    F -> <TT, Navigation>,
                },
                NavigationLayer: {
                    END -> ControlCode::Exit,
                    Y -> HOME,
                    U -> PAGEDOWN,
                    I -> PAGEUP,
                    O -> END,
                    H -> LEFT,
                    J -> DOWN,
                    K -> UP,
                    SEMICOLON -> RIGHT,
                },
            ),
        );
    }
}
```

The syntax here will be used to define layers for a keymapper tool that I am writing to bring keymapping/macro capabilities to arbitrary keyboards (ie no need for custom firmware in the keyboard itself). The reason I want to support an optional group in my syntax can be seen in the `ModLayer` definition where I want to notate layer-level settings in square brackets -- `[Active]`. In this case there is only one option, but in the future I want to support others like layer-level timing parameters for behaviors like tap toggle.

Anyway, I suppose I can work with the `bracketed!` macro by parsing the layer parameters in a function that returns an error and handling the error in the place where I would normally think to use something like `ParseBuffer.lookahead1` to choose whether to proceed based on whether or not there is a valid bracketed token stream ahead. I could be misunderstanding `ParseBuffer.lookahead1` here since it may not be expressive enough to properly handle grouped syntax parsing (maybe something like `Lookahead1.peek_delimited` would be necessary).

But it seems like the more ideal approach would be for users like me to call `$crate::group::parse_brace` or `$crate::group::parse_bracketed` (or even `$crate::group::parse_delimited`) directly and act appropriately on the resulting `Result`. I understand this is intentionally not exposed as a public API, but it's not clear to me why. I don't necessarily think anyone owes me an explanation, but I am curious if the maintainer would be open to a contribution that simplifies handling cases like mine. Or maybe what I'm trying to do simply diverges too much from proper Rust syntax :upside_down_face:.

Speaking of diverging from proper Rust syntax, while poking around it has occurred to me that I may run into another problem parsing part of my keyboard layer remapping definition syntax -- the turbofish approach to defining parameterized control codes, eg the `F -> <TT, Navigation>,` line in my example above means while the `ModLayer` is active and the F key is held down, activate the `Navigation` layer (TT stands for "Tap Toggle"). I bring this up because I noticed that `<>` doesn't get the same treatment as `[]`, `{}`, and `()`; this is understandable given their semantic difference in Rust, but I just thought I'd see if you have any suggestions for parsing syntax like this or if I would be better off going with something like `F -> (TT, Navigation),`.

I hope this doesn't come off as unappreciative or demanding, I really like this library so far and am finding it generally easy to work with. Thanks!

**Comment by waynr** [comment]
Coming at this again a couple days later, I realized a better way to use `braced` and `bracketed` to meet my needs:

```
pub struct LayerOpts {
    opts: Punctuated<Ident, Token![,]>,
}

impl Parse for LayerOpts {
    fn parse(stream: ParseStream) -> Result<Self> {
        let content;
        bracketed!(content in stream);
        Ok(LayerOpts{
            opts: content.parse_terminated(Ident::parse)?,
        })
    }
}

pub struct Layer {
    name: Ident,
    opts: Option<LayerOpts>,
    body: LayerBody,
}


impl Parse for Layer {
    fn parse(stream: ParseStream) -> Result<Self> {
        let name = stream.parse()?;
        let mut opts: Option<LayerOpts> = None;
        if let Ok(o) = stream.parse() {
            opts = Some(o);
        }
        Ok(Layer {
            name,
            opts,
            body: stream.parse()?,
        })
    }
}
```

That is, I call `bracketed!(content in stream)` in the `Parse` impl for `LayerOpts` and handle whichever `Result` variant is returned in the `Parse` impl for `Layer`. So yeah, feel free to ignore my previous word salad.

**Comment by waynr** [comment]
> That is, I call bracketed!(content in stream) in the Parse impl for LayerOpts and handle whichever Result variant is returned in the Parse impl for Layer.

Though now that I think about it just a bit more, i might still need to use `Lookahead1.peek` to distinguish between legitimate syntax errors and missing layer options... :thinking:

**Comment by dtolnay** [comment]
Per https://github.com/dtolnay/syn/issues/1046#issuecomment-943613875, let's only revisit this once the language allows question mark not to cause so many ambiguities.
