### ISSUE TITLE
Parse ~const modifier

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#1051]
- https://github.com/rust-lang/rust/pull/88328

**Comment by yaahc** [comment]
Hey, I'm interested in fixing this issue so that `cargo unstable-api` can start working again. I looked into it a bit and it seems like the right place to make the change would be to update `TraitBoundModifier` to add a `MaybeConst` variant or something, but this enum is pub and exhaustive, so I'm assuming this change can't be made under syn's stability guarantees.

Do you have an idea for how you are planning to add support for the const modifier? I'd be happy to implement it but I'm unsure of how to proceed so I figured I'd ask first.

**Comment by dtolnay** [comment]
You can stick it anywhere in the existing syntax tree. The syntax tree itself doesn't change until after the syntax gets stabilized.

For example any of the following would work:

- Parse the whole surrounding impl-block as `Item::Verbatim` instead of `Item::Impl`
- Convert the surrounding `PredicateType`'s `bounded_ty` to a `Type::Verbatim` and prefix the `~const` tokens onto it
- Insert `~const` as a segment in the `TraitBound`'s `path`
