### ISSUE TITLE
How to use the parse_file or parse_str function?

### ISSUE THREAD

**Issue by cicilzx** [dtolnay/syn#1462]
I followed the code example on the documentation and I was prompted that could not find syn::parse_file, what should I do?

I have add
```
syn = "2.0.17"
quote = "1.0"
```
in Cargo.toml, and here is my code:
```
use std::error::Error;
use std::fs::File;
use std::io::Read;

fn run() -> Result<(), Box<dyn Error>> {
    let mut file = File::open("path/to/code.rs")?;
    let mut content = String::new();
    file.read_to_string(&mut content)?;

    let ast = syn::parse_file(&content)?;
    if let Some(shebang) = ast.shebang {
        println!("{}", shebang);
    }
    println!("{} items", ast.items.len());

    Ok(())
}

fn main(){
    run();
}
```
![image](https://github.com/dtolnay/syn/assets/54731446/baed25d5-eb39-4a0f-9a27-4917e23ee9f3)
I'm confused and don't know what to do.

I have tried the code example of syn::parse_str, but it can't work either:
![image](https://github.com/dtolnay/syn/assets/54731446/86550182-41db-4b48-b6a7-624fa0a68dd7)
And this is my result:
![image](https://github.com/dtolnay/syn/assets/54731446/c345b368-69f4-48a4-9ec4-a56a2c0c8a39)

**Comment by atsmtat** [comment]
`syn::parse_file` is available only when you enable both `parsing` and `full` features. See the tiny box in [this](https://docs.rs/syn/latest/syn/fn.parse_file.html) page with text "Available on crate features ...".  `parsing` feature is default-enabled, but `full` is not. To enable it, you'll need following line in your Cargo.toml:

```toml
syn = { version = "2.0.17", features = [ "full" ] }
```

Similarly, the `fmt::Debug` trait on `syn::Expr` is available only when you enable `extra-traits` feature. Because you don't have it enabled, you're seeing the error while trying `syn::parse_str`.

**Comment by cicilzx** [comment]
Yeah, I have figured it out, thanks a lot!
