### ISSUE TITLE
`parse` should take a `&mut ParseStream`

### ISSUE THREAD

**Issue by rambip** [dtolnay/syn#1481]
Maybe there is an obvious reason, but I was not able to find any justification, so I will ask my question here.
Forgive me if it is naive.

Why does the `parse` function in the trait `Parse` take an immutable reference to a `ParseStream` ?
I had to read the docs for hours before understanding that each time you call `parse`, the stream mutates (It is never explained in the examples).

Since the `parse` function really mutates its input, I think it would be clearer to change its signature ...
And since the user entry-point is `parse_macro_input!`, I don't think it would change a lot of things for the user.

**Comment by bzm3r** [comment]
Maybe I am misunderstanding, but if I understand correctly, `ParseStream` doesn't "mutate" what it refers to, see the docs [here](https://docs.rs/syn/latest/syn/parse/struct.ParseBuffer.html) (recall that `ParseStream` is a an alias for `ParseBuffer`)  and the code [here](https://docs.rs/syn/latest/src/syn/parse.rs.html#245). 

So, the key points are:

1) `ParseStream` never mutates its input `TokenStream`, it is just a *cursor* on the input `TokenStream`. 

2) `ParseStream` does have interior mutability by the `Cell<Cursor>`, this is only in order to keep track of where it has read to.

**Comment by rambip** [comment]
I think you understood correctly.
But even if the ParseStream don't mutate the stream, it mutates the cursor, which is unexpected for the user !

Commonly, rust parsing library use `Parser` traits, and these traits implement a function taking a `&mut ref`

See [here](https://rust-unofficial.github.io/patterns/patterns/behavioural/visitor.html#example) for instance: even if `Expr` is not mutable, `Visitor` is.
This pattern feels way more intuitive for me

**Comment by dtolnay** [comment]
For anyone wondering about this, it would be an informative exercise to attempt to produce a compilable PR in which parser functions take `&mut`. I am confident you will not get very far before realizing it ends up being enormously detrimental to usability.
