### ISSUE TITLE
Fix `fold` and `visit` features

### ISSUE THREAD

**Issue by mystor** [dtolnay/syn#166]
`master` doesn't currently build when the `fold` or `visit` features are enabled. We should fix this.

**Comment by dtolnay** [comment]
I was hoping to put this off until everything else has settled down, right before releasing. Unfortunately if we need it for testing precedence, you are stuck cleaning up my mess. :frowning_face: The fix for #141 involved moving `Ident` fields that used to have to hold dummy values like `""` to places in the AST where they make more sense, or replacing them with `Option<Ident>`.

Will need to revert 627227845efcbf560ad2e640fe895b2bffc0b9be and 5d965c28120fd1611d2eeb51e0943457f482a8ee to restore the Travis build for these features.

**Comment by mystor** [comment]
This shouldn't have been closed until #169 is merged (silly over-eager github auto-closer).
