### ISSUE TITLE
Impl `ToTokens` for `syn::Error` and `syn::Result<T: ToTokens>`?

### ISSUE THREAD

**Issue by marcianx** [dtolnay/syn#1784]
I had a `foo: syn::Result<Expr>` and wrote:
```rust
foo
    .map(ToTokens::into_token_stream)
    .unwrap_or_else(syn::Error::into_compile_error)
    .into()
```

and it made me wonder:
1. Why can't we just do `quote! { #foo }` given that `syn::Error` has an idiomatic conversion to a `TokenStream` -- IOW, implement `ToTokens` for `syn::Result<T: ToTokens>`.
2. Does it make sense to also implement `ToTokens` for `syn::Error`?

Thoughts?

**Comment by dtolnay** [comment]
I think this would be a similar design mistake as Serde implementing `Serialize` and `Deserialize` for `Result<T, E>`. The way it would play out in practice is the intentional uses would be rare and the mistaken uses (someone wrote too few `?`) would be rampant and hard to identify. I think `.unwrap_or_else(syn::Error::into_compile_error)` is the right level of easy and clear for the cases where this is the behavior someone wants.
