### ISSUE TITLE
Conversion from Tokens to proc_macro::TokenStream

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#179]
What is the story behind https://github.com/dtolnay/quote/commit/0b8ebcbb9a2b021ae1df7411bf67d8c6d661e3da? Relevant to #178.

**Comment by alexcrichton** [comment]
Oh I added that commit initially to `quote` because I thought it was necessary-ish for https://github.com/dtolnay/syn/pull/165 but it ended up not being so, so I made the API more conservative. I've been thinking about the `proc_macro` vs not situation in the sense that crates like `quote` and `syn` are useful in standalone programs because there's no dependency on `proc_macro`. With recent changes, however, I wasn't sure if we wanted to preserve that or specifically avoid that. For example there's no need for `proc-macro2` to depend on the `proc_macro` crate itself.

In any case ergonomically it seems quite nice to have, so any objections to re-adding?

**Comment by mystor** [comment]
I talked at the all hands a bit about this, and I think the plan for the future is to make sure that `proc_macro` works outside of the compiler in standalone crates before it is stabilized. I think that we shouldn't be trying to avoid `syn` or `quote` from depending on `proc_macro`, as it will make the API a lot cleaner, and keep the interface uniform between being within procedural macros and in independent programs.

In addition, eventually being able to drop having to build the lexer could really help with compile times ^.^.

**Comment by alexcrichton** [comment]
I've opened https://github.com/dtolnay/quote/pull/40 to "officially" add it
