### ISSUE TITLE
Produce proc_macro2::TokenStream instead of quote::Tokens

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#180]
Do these need to be different types? Conceptually they are both `Vec<TokenTree>`. Would it be possible for `quote!` to produce `proc_macro2::TokenStream` (and eventually, `proc_macro::TokenStream`)?

**Comment by mystor** [comment]
The biggest disadvantage of this is that `TokenStream` doesn't have near as large of an API surface as `Vec<TokenTree>` - for example it isn't possible to `.push()` a new `TokenTree` onto the end at the moment. We'd have to change the `ToTokens` API a lot, and do some tricks to use `Vec<TokenTree>` while building up the result of `quote!()`, in order to avoid the cost of constantly destructing and re-building `TokenStream` objects.

I think for now using a different type is probably our best option.
