### ISSUE TITLE
consider moving back to nom

### ISSUE THREAD

**Issue by Geal** [dtolnay/syn#195]
Hi!

I'm currently in the process of rewriting large parts of nom for the 4.0 release, and I think it will get closer to how synom works. Here are some changes I'm currently doing:
- moving from `IResult` to `Result`. The `Incomplete` case is now merged in the `Err` part
- calculations for `Incomplete` are removed. Those were not very useful and generated an awful lot of code
- adding an "unrecoverable error" alternative. Right now you can use `return_error!` to backtrack directly out of the current function instead of testing other branches of `alt!` (or other branching combinators). This would now cross a function's boundary
- simplifying custom error types usage (and avoiding most type inference errors)
- maybe merging the "simple" and "verbose" error management, if I can manage to make it fast enough

This is still very soon and a work in progress (you can follow it on https://github.com/Geal/nom/tree/result ), but I would like to see if it could compile fast enough to replace synom. Do you have code examples that would work well for those benchmarks?

I'm currently messing with syn's source to try and make it compile with nom 3.2, then with my in progress version.

**Comment by Geal** [comment]
okay, so, an update on this. I published a 4.0.0-alpha1 of nom with all of the above, and an additional `AtEof` trait for the input type, to indicate if we can return `Incomplete`. From my recent tests, when `at_eof()` returns a constant, it tends to remove most of the `Incomplete` related code.
The error type is also more interesting now, returning an error code and a slice of the input even in the common case (while being faster than the original system).

Overall, this nom version is faster than before, and there's still a lot of low hanging fruit to get, now that the core types have changed.
Do you think it would be interesting to try and replace parts of synom now?

**Comment by dtolnay** [comment]
Sure, let's give it a try and compare the two. 👏

**Comment by Geal** [comment]
so, for now, I was able to replace all the combinators except `many0`, `reject` (not in nom), `do_parse` (nom does not have the "mut" case), and `input_end`.

For the compilation times (from clean project, `cargo build --release`), I have for syn:

```
real    0m18.249s
user    0m17.564s
sys     0m0.566s
```
For syn with nom:

```
real    0m23.099s
user    0m26.797s
sys     0m0.863s
```

So I guess I still have some work to do :)
Do you have benchmarks running syn somewhere, that I could reuse to test the nom version?

**Comment by Geal** [comment]
in debug, I get for syn:

```
real    0m6.987s
user    0m9.084s
sys     0m0.861s
```

and syn with nom:

```
0m7.867s
0m13.810s
0m0.988s
```
Still a bit much but that looks bearable

**Comment by dtolnay** [comment]
I do not have syn benchmarks because so far we have optimized only for compile time, not for performance. 10x - 100x slower than the compiler's parser is fine because macro expansion is a small part of the compile time for the end user and parsing in proc macros is a small part of macro expansion.

Could you share your code in a fork or PR? I would be interested in how our [cursor over token stream](https://github.com/dtolnay/syn/blob/302afd282be33c1ba753d9a43672c6144b30f857/synom/src/cursor.rs) interacts with nom, what sort of errors you get from nom combinators that do not make sense on a token stream, etc.

Do you have any ideas for how to handle documentation after switching to nom? Currently we have reasonably thorough [proc-macro-specific documentation](https://github.com/dtolnay/syn/blob/302afd282be33c1ba753d9a43672c6144b30f857/synom/src/helper.rs#L32-L61) on all of the synom combinators.

We should also make sure we understand: what advantages do users of syn gain in exchange for 12% slower compile time?

**Comment by Geal** [comment]
I put the code there: https://github.com/Geal/syn/commits/master
There are no issues with Cursor since most of the combinators do not even depend on the input type.
For the documentation, now the doctests must import nom to compile. I'd suggest moving the documentation to a module level doc. Those exampes are of better quality than nom ones and fit well to syn's use cases, so it makes sense to keep them somewhere.

About the benefits, for now, I'd say there are none. I just replaced the combinators to see if it would fit with nom. Now that this is apparently ok, I can get to the more interesting parts:
- improving compilation times for nom. If you have suggestions there, I'm interested. I quite liked the idea of separating a many0 case in a function instead of reusing the macro
- maybe do something useful with `ParseError`, since nom's [basic error type](https://github.com/Geal/nom/blob/master/src/simple_errors.rs#L19-L22) embed an input slice. That would allow showing to the user which part of the input could not be parsed
- the "Failure" case would allow faster parsing in some cases, allowing `alt!` to return directly instead of trying every alternative

If that's not convincing enough, it's ok :) synom now provides me with a good project to test optimizations on

**Comment by bryteise** [comment]
@dtolnay Maybe this comment should exist somewhere else but becuase synom doesn't exist in the latest release (or a standalone as far as I could tell), it is a real pain to package syn. I need to get the tar file from crates.io of synom and then get the old release of syn because synom requires that version in order to just build the current version of syn. Is this the intended build flow because it is really unpleasant to work with.

**Comment by dtolnay** [comment]
Closing because I don't intend to pursue this, but I am glad we provide you with a valuable test environment and I look forward to those improvements.
