### ISSUE TITLE
Test out LALRPOP integration

### ISSUE THREAD

**Issue by alexcrichton** [dtolnay/syn#207]
Ideally procedural macros should be easy to write with a parser generator like LALRPOP, we should test that out and assert it!

**Comment by alexcrichton** [comment]
Note that this shouldn't block a release or anything, I mostly just opened it up on a whim! It's also fine if you'd prefer to close.

**Comment by dtolnay** [comment]
I don't think integration with Syn will happen because LALRPOP needs to understand the entire input grammar, and that does not play well with knowledge of the grammar living in Syn's parser functions. But I put together a [proof of concept of using LALRPOP to parse procedural macro input](https://github.com/dtolnay/lalrproc) without Syn.
