### ISSUE TITLE
syn::Item does not implement neither Debug nor Display

### ISSUE THREAD

**Issue by gnzlbg** [dtolnay/syn#220]

**Comment by dtolnay** [comment]
Debug impls are slow to compile and most proc macros will not use them. There is a cfg you can set to have Debug impls for all the AST structs: `features = ["extra-traits"]`.

Instead of Display which is for printing as a string, the AST structs have ToTokens which converts to tokens usable in a proc macro. `quote!(#my_item)` renders `my_item` as a `quote::Tokens`. Then if you really really need a string you can call `to_string()` on the Tokens.
