### ISSUE TITLE
Add Copy + Clone for Visibility.

### ISSUE THREAD

**Issue by kgv** [dtolnay/syn#273]
Visibility does not implement Copy and Clone. But it is very useful.
Is there any special reason not to implement this?

**Comment by dtolnay** [comment]
In the 0.11.11 released version of syn, Visibility does implement Clone. It cannot implement Copy because for a restricted visibility like `pub(in some::module)` the Visibility needs to own the content of the "some::module" path, and types that own something generally cannot implement Copy.

Same thing in the master branch except the `clone-impls` cfg controls whether Clone impls exist, because they tend to hurt compile time.

**Comment by kgv** [comment]
Sorry, my fail. I used `default-features = false` and I did not notice that the `clone-impls` feature exist.
