### ISSUE TITLE
What's blocking 1.0?

### ISSUE THREAD

**Issue by sgrif** [dtolnay/syn#293]
The API for syn seems to be reasonably stable. What would be required for this crate to release a 1.0 version?

**Comment by dtolnay** [comment]
The API is not at all stable. 😆 We merged probably about 100 breaking changes in the past month.

**Comment by sgrif** [comment]
I guess I haven't updated in a while then. I don't recall updating syn breaking us since 0.10 -> 0.11.

**Comment by sgrif** [comment]
The question still stands though -- What's the source of the instability? Is there a known set of features that are missing which are likely to require breaking changes?

**Comment by dtolnay** [comment]
Yep, we are retooling the entire crate to support the new token-based procedural macro API in nightly https://github.com/rust-lang/rust/issues/38356. We need the ability to propagate hygiene information from individual input tokens into the output tokens. That requires redesigning all the parser entry points to operate on tokens as input rather than strings as input, and it requires replacing the "abstract syntax tree" in 0.11 with a "concrete syntax tree" that can track all this hygiene information at the granularity of individual input tokens.

Do a `cargo doc --all-features` from master and check out the redesign.

After that, we need to build enough experience with token-based procedural macros to work out the right idioms for parsing and code generation and error handling, and update our API to take those into account. And we need to stabilize at least the subset of https://github.com/rust-lang/rust/issues/38356 that the parser and quasi-quoter rely on, since that stuff will now be in the public API of syn.

**Comment by mystor** [comment]
I should also note that once we reach that point we will never be able to profess to have a truly stable API, because we need to support adding new AST variants etc. as they are added to rust the language. If we ever hit 1.0, we'll have to release a 2.0 soon after when we merge a new RFC, and so on.

**Comment by mystor** [comment]
If rust gets extensible enums we might be able to design a forward-compatible API, but that's a way off...

**Comment by sgrif** [comment]
Gotcha. It sounds like it's quite a ways from happening then. Thank you for taking the time to explain this to me. :)

**Comment by sgrif** [comment]
> I should also note that once we reach that point we will never be able to profess to have a truly stable API, because we need to support adding new AST variants etc. as they are added to rust the language.

I disagree with this, and that extensible enums are needed for this. Most crates out there have something like this:

```rust
pub enum VariantsAddedLater {
    PublicVariant,
    MorePublicVariants,
    #[doc(hidden)]
    __Unknown, // Match against `_` instead, more variants might be added in the future.
}
```

This is perfectly suitable for that task

**Comment by JelteF** [comment]
What's the current status of this, January 2018 is quite some time ago now? 
Also, I think it makes sense to reopen this issue.

**Comment by JelteF** [comment]
>If rust gets extensible enums we might be able to design a forward-compatible API, but that's a way off...

This is close to happening now: https://github.com/rust-lang/rust/issues/44109

**Comment by Centril** [comment]
Even with `#[non_exhaustive]` I think 1.0 would be problematic as Rust's syntax may for example combine productions into another for simplification purposes. For example, if `let ps = e` becomes a syntactic expression then you no longer have `IfLet` and `WhileLet` expressions as separate constructs. Another example is `..` rest patterns which would simplify tuple, tuple struct, and slice patterns. Simply adding variants would not be enough as you would need to decide whether to make your old `IfLet` variant into one that is never constructed by the parser (which seems like a breaking change dynamically but not statically).

**Comment by JelteF** [comment]
I don't really understand why `syn` couldn't keep them as separate constructs in those cases and only add a construct for the the new thing. The AST elements of `syn` might not match 100% percent what the compiler actually uses internally, but that's kind of the point of `syn` right? It's also possible that I'm missing something. If so, could you expand a bit more on what you mean?

Furthermore, I'm not saying `syn` should never have a major version update. Incrementing the version and doing a breaking change is still an option, if it would improve the API significantly. I'm just saying that it would be nice if it could commit to a stable API for a while.

**Comment by Centril** [comment]
> I don't really understand why `syn` couldn't keep them as separate constructs in those cases and only add a construct for the the new thing.

Sure, you could absolutely do that technically. The downside is that you will accumulate garbage and convoluted ways of parsing in favor of stability. Users will also need to handle this duplication in the API which could be surprising. For example, right now I'm implementing an RFC which will transform:

```rust
enum PatKind {
    // other stuff elided...
    TupleStruct(Path, Vec<P<Pat>>, Option<usize>),
    Tuple(Vec<P<Pat>>, Option<usize>),
    Slice(Vec<P<Pat>>, Option<P<Pat>>, Vec<P<Pat>>),
}
```
into:
```rust
enum PatKind {
    // other stuff elided...
    Rest,
    TupleStruct(Path, Vec<P<Pat>>),
    Tuple(Vec<P<Pat>>),
    Slice(Vec<P<Pat>>),
}
```

Say `syn` cuts a 1.0 right now. To support this you'd need to add all the 4 new variants in addition to the old ones and then pay special attention to putting `..` in the old variants when it is the only one there.

> The AST elements of `syn` might not match 100% percent what the compiler actually uses internally, but that's kind of the point of `syn` right? 

Sure; the difference between now and syn 1.0 is that syn does a good job of tracking the compiler in terms of the AST.

> Furthermore, I'm not saying `syn` should never have a major version update. Incrementing the version and doing a breaking change is still an option, if it would improve the API significantly. I'm just saying that it would be nice if it could commit to a stable API for a while.

My concern is that once syn becomes 1.0 it will want to stay there for a long time (consider how long serde has been 1.0) and that this will a) put pressure on slowing down changes to Rust's surface and AST, b) add garbage over time to `syn` which users of `syn` would need to handle. I guess it depends on how long an 1.0 lasts...

**Comment by JelteF** [comment]
I think I might missing the needed context for those type changes, but to me they only look like a simplification, i.e. you can express the same patterns with the old as the new types just in different ways.

> Sure; the difference between now and syn 1.0 is that syn does a good job of tracking the compiler in terms of the AST.

To me that seems useful, but not really a goal of `syn`. Looking at the types from your example. The AST is [already quite differently defined] (e.g. different type names, extra fields, structs inside tuple enums).

> a) put pressure on slowing down changes to Rust's surface and AST

Is difficulty of adding new syntax to `syn` really a consideration of the Rust design process? 

> b) add garbage over time to syn which users of syn would need to handle. I guess it depends on how long an 1.0 lasts...

I think this is the case for making any library version 1.0. There's always a tradeoff between stability and collection of garbage. If syn is still expected to do major changes in the API, I think it would not yet be a good time for 1.0. However, if it is only expected to change because of additions to the Rust AST, I think some garbage is better breaking changes. At least to a certain point, at which all acquired garbage is cleaned up and a new major version is created. So, to restate my main point for clarity: I don't see a difference between `syn` and other libraries.

**Comment by Centril** [comment]
> I think I might missing the needed context for those type changes, but to me they only look like a simplification, i.e. you can express the same patterns with the old as the new types just in different ways. So I don't see why `syn` would have to add these new types at all.

So the context here is that [RFC 2359](https://github.com/rust-lang/rfcs/blob/master/text/2359-subslice-pattern-syntax.md) adds `..` as a pattern, e.g. you can write `#[cfg(FALSE)] fn foo( .. : u8 ) { ... }`. This clearly is *not representable* in the old AST so you would need the new form to do it. However, now you also have to ensure not to construct `::Rest` in the case of e.g. `[x, .., y]` as this would be a breaking change dynamically (but not statically).

(Sometimes, but rarely, Rust also removes unstable syntax)

> Looking at the types from your example. The AST is [already quite differently defined] (e.g. different type names, extra fields, structs inside tuple enums).

Field and type names, preserving more spans, and structs inside tuple enums are really not fundamental. They seem like minor differences where syn e.g. preserves more information and has perhaps a more modern API than libsyntax.

> Is difficulty of adding new syntax to `syn` really a consideration of the Rust design process?

One instance of this was the turbofish discussions. It doesn't happen frequently, but it could become an issue... or at minimum I'd like to see the case for it not being so.

> However, if it is only expected to change because of additions to the Rust AST, I think some garbage is better breaking changes. At least to a certain point, at which all acquired garbage is cleaned up and a new major version is created. So, to restate my main point for clarity: I don't see a difference between `syn` and other libraries.

Well `syn` would be similar to other libraries where the "feet under them" changes quickly. I think this all depends on how long a 1.0 is supposed to last. Are we talking about 1/2 years, 1 year, 2, ... ?
