### ISSUE TITLE
`<Lifetime as ToTokens>` is missing the apostrophe

### ISSUE THREAD

**Issue by mcarton** [dtolnay/syn#30]
If you use `quote!` on a `syn::Generics`, it gives `<a, T>`. It should be `<'a, T>`.

**Comment by dtolnay** [comment]
This `syn::Generics` includes a `syn::Lifetime` that you created yourself right? It looks like the Lifetimes parsed by syn [always include the apostrophe](https://github.com/dtolnay/syn/blob/359023034f59726eeea943dd17c7c3457b967921/src/generics.rs#L205).

I want the apostrophe to be included in the Lifetime name because this is how libsyntax does it. Here is what I did to check:

Create main.rs:

```rust
fn f<'a>() {}
```

Run `rustc -Z ast-json main.rs`. The following appears in the output:

```json
"lifetimes": [
  {
    "attrs": {
      "_field0": null
    },
    "lifetime": {
      "id": 5,
      "span": {
        "lo": 5,
        "hi": 7
      },
      "name": "'a"
    },
    "bounds": []
  }
],
```

The lifetime is `"'a"` not just `"a"`.

Can you think of a better way to handle this? Maybe it should panic if there is a lifetime that does not start with apostrophe? Or maybe add the apostrophe if one is missing? Or maybe just document that user is responsible for the apostrophe?

**Comment by mcarton** [comment]
Ah! I never noticed the lifetime *name* included the `'`. `syn` behavior seems legit then.
Some documentation would be enough I guess. Maybe a panic in `syn::Lifetime::new` if there is no `'`.
Thanks!
