### ISSUE TITLE
Can't run tests on stable or without --all-features

### ISSUE THREAD

**Issue by sgrif** [dtolnay/syn#325]
This makes contributing very difficult. I expected `cargo test` to work. After digging into `.travis.yml` I figured that `cargo test --all-features` is what I need, but that doesn't work on stable. It also looks like tests aren't run against stable in CI?

**Comment by mystor** [comment]
Our tests compare the parsing of syn to `libsyntax` which is a fundamentally unstable API.

We unfortunately can't run these tests on a stable version of rust.

**Comment by dtolnay** [comment]
I agree that there isn't going to be a way for us to run all tests on stable but I sympathize that this can make contributing tricky. Let's use [`rustc_version`](https://crates.io/crates/rustc_version) in a build script to detect when we are testing on nightly, otherwise replace the precedence and round-trip tests with a single #[test] that unconditionally panics with a message that says not all tests ran with an explanation. That way that rest of the tests actually run and you get something more helpful than:

```
error[E0554]: #![feature] may not be used on the stable release channel
  --> tests/test_round_trip.rs:10:1
   |
10 | #![feature(rustc_private)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
```
