### ISSUE TITLE
panics with "Unrecognized literal"

### ISSUE THREAD

**Issue by dwrensha** [dtolnay/syn#345]
The following programs unexpectedly panic:

```rust
extern crate syn;

fn main() {
    let _ = syn::parse_file("dc0<{dc0</*!x*'!*/!L:,*}");
}
```

```rust
extern crate syn;

fn main() {
    let _ = syn::parse_file("dc0</**!\x1e*ee\x0ae/!!\"{e*/0!7");
}
```

```rust
extern crate syn;

fn main() {
    let _ = syn::parse_file("dc0<///!{\x0a(continue|||||self||||)");
}

```

**Comment by dtolnay** [comment]
Thanks! I believe these all minimize to `syn::parse_file("ident < /*! */")`.

There were two things going wrong:

- Since this is at the top-level of a file, the only syntax that could begin with an ident rather than a keyword like `struct` or `fn` is a macro invocation. It was parsing the path of the macro invocation, which in nightly can be a full path like `a::b::m!()`. But generic arguments in a macro path should be disallowed so it should have failed on the `<` token. Fixed in d69fc2b26a812b14ec4d0f8f628b227303a5787f.

- It was parsing the `<...>` as generic arguments, specifically [const generics](https://github.com/rust-lang/rfcs/blob/master/text/2000-const-generics.md) because the argument is what proc_macro considers a literal. But doc comment literals are not considered literals in Syn. Fixed in 7037c9b9f30803400e8bdd031a833607d154cbec.
