### ISSUE TITLE
Document how to use compile_error for error reporting

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#352]
If you panic in a proc macro:

```rust
panic!("boo");
```

```
error: proc macro panicked
 --> src/main.rs:6:5
  |
6 |     demo!();
  |     ^^^^^^^^
  |
  = help: message: boo
```

If you expand to [`compile_error!`](https://doc.rust-lang.org/std/macro.compile_error.html):

```rust
quote! {
    compile_error!("boo");
}
```

```
error: boo
 --> src/main.rs:6:5
  |
6 |     demo!();
  |     ^^^^^^^^
```

**Comment by federicomenaquintero** [comment]
I'm testing error reporting and ran into this issue; I'd like to write the relevant docs.

Just to see if we are thinking of the same thing... I modified the `lazy_static` example provided with syn to have this:

```
 #[proc_macro]
 pub fn lazy_static(input: TokenStream) -> TokenStream {
-    let LazyStatic { visibility, name, ty, init } = syn::parse(input).unwrap();
+    let LazyStatic { visibility, name, ty, init } = match syn::parse(input) {
+        Ok(o) => o,
+        Err(e) => {
+            let desc = e.description();
+            let tokens = quote! {
+                compile_error!(#desc);
+            };
+
+            return tokens.into();
+        }
+    };
+
     let def_site = Span::def_site();
```
(which is not the nicest Rust style, but I didn't want to put the whole function body into a match clause).

Then I modified the part of the example that uses this `lazy_static!` proc macro:

```
lazy_static! {
    plonk static ref USERNAME: Regex = {
```

And inded the compiler gives me `error: failed to parse`, instead of `error: proc macro panicked` with a `help: message: failed to parse` later.

Is this the sort of thing you'd like in the documentation?

I suppose I should draw a distinction between bugs/assertions in the proc macro code (which should panic), and errors in the user's code that are detected by the proc macro - those should compile_error?

**Comment by dtolnay** [comment]
Added this documentation in 9317120b961e1c84d83033dcd09e4781728bf940.
