### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by sgrif** [dtolnay/syn#387]
I saw this comment in Gitter today:

> Urgh, quote 0.5 and syn 0.13 are out, going to be a fun week

To which I immediately thought to check the changelog to determine whether projects I maintain are going to be affected or not. However, it seems like that's not being recorded.

In my opinion, this is a critical piece of infrastructure to communicate both what has changed, and how to migrate. I highly recommend following the format presented by https://keepachangelog.com/

**Comment by dtolnay** [comment]
Thanks for the issue. I am closing because I don't believe a changelog here would be valuable. You can model Syn releases as snapshots of the Rust syntax (both stable and unstable) as of the time of release. In that sense this library is less like Serde or Diesel (which have changelogs) and more like libsyntax / rustc-ap-syntax (where the character of changes makes a changelog not useful; you upgrade by fixing what the compiler tells you). The decision whether to upgrade will depend on how bleeding-edge of syntax you want to support.

**Comment by sgrif** [comment]
0.11 -> 0.12 was not at all about changes in Rust syntax. I have no way of knowing that the changes between 0.12 -> 0.13 are related to that without such a document. The PRs I authored also aren't related to changes in Rust syntax, and are something that would not be easily discoverable without a changelog
