### ISSUE TITLE
syn without derived for rust_swig

### ISSUE THREAD

**Issue by Dushistov** [dtolnay/syn#435]
Hi,

I would like port to my project [rust_swig](https://github.com/dushistov/rust_swig)
to syn because `syntex` is not supported any more.

However my crate is not based on derived, so after reading the documentation I have a few questions.
To put it short, my crate parses macroses with a syntax like this:

```Rust
foreigner_class!(class Foo {
    self_type Foo;
    constructor Foo::new(_: i32) -> Foo;
    method Foo::set_field(&mut self, _: String);
    method Foo::f(&self, _: i32, _: i32) -> Option<i32>;
    static_method f2(_: i32) -> Vec<i32>;
});
```
and translates it to the glue code (Rust/C/C++ or Rust/Java) that makes possible to write in C++ (or Java):

```C++
Foo foo {5};
foo.set_field("boo");
``` 

`syntex` provides a framework to write such kind of macros, but it looks like `syn` is mostly
for `derive` extensions, so I have several questions: 

1. Should I use syn::visit_mut to find `foreigner_class!` in crate and replace with generated code?
2. After code generation can I remove  macro item( `foreigner_class!`) and replace it with several
 `trait`s, `fn`, `struct`, etc.?
3. Can I use part of `syn` that parses functions signatures?
   For example, parsing of  `Foo::f(&self, _: i32, _: i32) -> Option<i32>;`
   consists of parsing path `Foo::f`, and parsing impl method signature:
   `(&self, _: i32, _: i32) -> Option<i32>` and then parsing `;`.
4. Can I report errors bounded to positions of tokens later?
  For example, I parsed `Foo::f(&self, _: i32, _: i32) -> Option<i32>;` and obtained each argument type
  `i32`, `i32`, `Option<i32>`, and after parsing the whole file, and parsing some rules,
  I want to report that there is no known conversation from `Option<i32>` and `boost::optional<int32_t>`,
  and in the error report show the place where I found  `Option<i32>`. I see that it is possible to report
  errors during parsing, but what about afterwards?

/cc @dtolnay  
/cc @mystor

**Comment by dtolnay** [comment]
Everything you listed is possible to implement using Syn, but note that Syn is a parser while libsyntax contains a lot of other surrounding infrastructure other than a parser.

1. I would recommend not using visit_mut because then you end up with all of the user's original code in OUT_DIR. I think ideally only the generated code would go in OUT_DIR.

2. Removing the macro invocations would be more simply implemented by exporting an empty `macro_rules! foreigner_class { () => {} }`. Or `foreigner_class!` could include files from OUT_DIR by expanding to `include!(concat!(env!("OUT_DIR"), "/foreigner_class/", stringify!(Foo), ".rs"))`.

3. Yes, all the built in parsers are exposed as implementations of the [`Synom`](https://docs.rs/syn/0.14/syn/synom/index.html) trait and can be combined together to parse a custom syntax. [`lazy-static`](https://github.com/dtolnay/syn/tree/0.14.2/examples/lazy-static) gives one example of parsing a custom syntax using Visibility, Ident, Type, and Expr as building blocks.

4. Every input token is preserved in the syn AST and carries a [`Span`](https://docs.rs/proc-macro2/0.4/proc_macro2/struct.Span.html) which has start and end line/column information for error reporting, though this requires the `procmacro2_semver_exempt` setting of proc-macro2.
