### ISSUE TITLE
Cannot parse enum derive input with discriminant set by a macro

### ISSUE THREAD

**Issue by AdnoC** [dtolnay/syn#452]
With the default set of features, `syn` fails to parse derive input for enums with their discriminant set by a macro.

Using full features fixes the problem, but shouldn't the default be able to parse all derive input?

Minimal example:

```rust
extern crate syn;

fn main() {
    let works = "pub enum Test { A = 0, B = 2, C = val, }";
    let _: syn::DeriveInput = syn::parse_str(works).expect("`works` failed to parse");

    let fails = "pub enum Test { A = get_num!(), B = 2, C = val, }";
    let _: syn::DeriveInput = syn::parse_str(fails).expect("`fails` failed to parse");

}
```

errors with

```
thread 'main' panicked at '`fails` failed to parse: ParseError(Some("failed to parse derive input: failed to parse"))', libcore\result.rs:945:5
```

---------------

Or, given a custom derive `EnumWithMacro`:

```rust
macro_rules! get_an_isize {
    () => (0_isize)
}

#[derive(EnumWithMacro)]
enum UsesMacroDiscrim {
    VarA = get_an_isize!(),
    VarB = 3,
}
```

errors with

```
error: proc-macro derive panicked
 --> src\lib.rs:6:10
  |
6 | #[derive(EnumWithMacro)]
  |          ^^^^^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: ParseError(Some("failed to parse derive input: failed to parse"))
```

**Comment by dtolnay** [comment]
> shouldn't the default be able to parse all derive input?

I do not believe so. As below, parsing all derive input requires parsing all possible Rust source code, which unreasonably affects compile time for the vast majority of derive inputs which are simple. A line needs to be drawn somewhere.

```rust
enum Wild {
    V = {
        fn f() {
            // suddenly just parsing the discriminant requires parsing all
            // possible Rust code
        }
        0
    },
}
```

If the use of a macro in the discriminant is important across all or most users of `derive(EnumWithMacro)` then the crate providing `derive(EnumWithMacro)` will want to enable the `"full"` feature of Syn. Otherwise individual users of `derive(EnumWithMacro)` can enable the `"full"` feature of Syn as needed.

**Comment by AdnoC** [comment]
Ah, thats true. I'll close this issue then.
