### ISSUE TITLE
Public bridge between low and high level parser APIs.

### ISSUE THREAD

**Issue by mystor** [dtolnay/syn#479]
I had some code in a project where I was constructing a `TokenBuffer` from a `TokenStream` myself, and then using the `Cursor` to walk along it. It appears as though there is no public mechanism currently to get from a `TokenBuffer` or `Cursor` object to a `ParseBuffer`. It could be nice if some public API for this was provided beyond using `Parser::parse2` on a lambda.

**Comment by dtolnay** [comment]
Thanks! You are right, this is not well supported now.

This is going to be tricky because `Parser::parse2` is actually what detects tokens that were never parsed -- even inside of nested groups. That's how we get away without any sort of checking for remaining tokens in impls like this one:

https://github.com/dtolnay/syn/blob/719ad5a1c1944c3b413179371f4a621c010eeb8f/src/ty.rs#L455-L465

Without some sort of explicit check that `content.is_empty()` at the end of this code, those "unexpected token" errors need to be triggered from Drop impls and/or from some central place afterward. And as Drop impls cannot return error, that central place ends up being `Parser::parse2`.

That means going from `Cursor` temporarily to `ParseStream` and then back to `Cursor` is not simple (or not obvious to me how to make it simple).

I would like to understand whether more of your code could be written in terms of `ParseStream`. If all of it can, that seems better. If some of it needs to remain using `Cursor`, can just those parts be performed using a call to [`ParseStream::step`](https://docs.rs/syn-next/0.15.0-rc3/syn/parse/struct.ParseBuffer.html#method.step)? The closure argument to `step` effectively has the same signature as `Synom::parse`. Either way this would let `ParseStream` own the entire process and perform the right checks for unparsed tokens.

**Comment by mystor** [comment]
I was able to fairly easily rewrite the logic to work with `ParseStream` (It wasn't super performance sensitive, so I just used `ParseBuffer::fork`).

I didn't think of the bracketed-parser issues, so it makes sense why the wrapper method call is needed. I suppose I would like a `parse_cursor` mechanism which takes in a `Cursor` and has the same semantics as `parse2(F, cursor.token_stream())`, but without the token copies. 

e.g.
```rust
trait Parser : Sealed {
    fn parse_cursor(self, cursor: Cursor) -> Result<T>;

    fn parse2(self, tokens: TokenStream) -> Result<T> {
        let buf = TokenBuffer::new2(tokens);
        self.parse_cursor(buf.begin())
    }
}

impl Parser for ... {
    fn parse_cursor(self, cursor: Cursor) -> Result<T> {
        let state = private::new_parse_buffer(Span::call_site(), cursor, Default::default());
        let node = self(&state)?;
        state.check_unexpected()?;
        if state.is_empty() {
            Ok(node)
        } else {
            Err(state.error("unexpected token"))
        }
}
```

**Comment by dtolnay** [comment]
I agree with the edit: it's possible someone would want to parse some stuff with `Cursor`, then parse some `T: Parse`, then keep going with the rest of the token using `Cursor`.

Since you got it working, how about we wait for one or two more use cases to crop up in this thread and then try to generalize and design a solution. I do think there is work needed here but I think we can address it backward compatibly.

**Comment by lnicola** [comment]
> Since you got it working, how about we wait for one or two more use cases to crop up in this thread and then try to generalize and design a solution.

`tower-web` has [this snippet](https://github.com/carllerche/tower-web/blob/2fb07a75272a120f0bffc165961b8d5d9c8c5fb1/tower-web-macros/src/resource/attr.rs#L128-L133) which no longer compiles with `syn 0.15`. I'm barely familiar with the `syn` API, maybe you could suggest an alternative.

**Comment by chpio** [comment]
the doc on [`fork`](https://docs.rs/syn/0.15.14/syn/parse/struct.ParseBuffer.html#method.fork) says
```rust
// Do not do this.
if input.fork().parse::<Expr>().is_ok() {
    return input.parse::<Expr>();
}
```

Maybe we could add a "higher" level step method? Which would create a "checkpoint" by getting the current cursor, then call the closure with self and replace the current cursor with the checkpoint cursor if the return value of the closure is an error?

**Comment by dtolnay** [comment]
@chpio I would deliberately try not to encourage that style of parsing. Nom behaves like that and it makes it impossible to produce good error messages. There is no way to tell whether the user meant to write an Expr but made a syntax mistake inside of it, or meant to write whatever they were supposed to write if not an Expr.

**Comment by CAD97** [comment]
[This Twitter tree seems relevant.](https://twitter.com/CAD97_/status/1085242786717335556)

Especially with the increasing significance of functionlike macros (aka macros with their own syntax that isn't necessarily just Rust's), I think having a way of doing speculative parsing is desirable. In fact, doctests require this kind of speculative parsing [since they require grabbing [`(OuterAttribute | ExternCrate)* Item*`](https://twitter.com/QuietMisdreavus/status/1085323569377222656?s=20). Any `A* B*` where you can't tell `A` from `B` for certain in the first three tokens requires speculative parsing. I suppose the doctest is roughly better for error reporting since I think `B ⊇ A` holds.

[It's actually mostly possible using just the currently public API](https://t.co/0Ff1g7pYU9), it just requires `unsafe` to guarantee the cursor belongs to the correct parse stream.

You can definitely hold that speculative parsing is not the best practice. But I don't think making it impossible is sustainable if you want to keep syn as _the_ solution for writing procedural macro code, because some functionlike macros _are_ going to want and/or need speculative parsing methods. Adding a join (unfork) would solve that problem nicely.

**Comment by dtolnay** [comment]
I believe #649 has implemented the missing piece here. Now it is possible to do speculative parsing on ParseStream (instead of Cursor / step) without reparsing the same tokens on both the fork and the original stream.

**Comment by clouds56** [comment]
>  it's possible someone would want to parse some stuff with Cursor, then parse some T: Parse, then keep going with the rest of the tokens using Cursor.

I think it's not that hard to provide an helper method
```rust
pub fn parse_cursor<T: Parse>(cursor: Cursor) -> Result<(T, Cursor)> {
    let scope = Span::call_site();
    let unexpected = Rc::new(Cell::new(Unexpected::None));
    let state = new_parse_buffer(scope, cursor, unexpected)
    let node = T::parse(&state)?;
    state.check_unexpected()?;
    Ok((node, state.cell.get()))
}
```

I'd like this since I'm building an finite automata for parse with `Cursor<'_>`, and sometimes I'd like to use high level API (e.g. for parsing ItemFn).
I may use `ParseStream` but `fork`/`advance` at every step is very annoying and make it hard to find errors (`cell` is used in `ParseStream` which inner states may mutate when passing into sub-aotomata).
So I still prefer the `Cursor` version and if `parse_cursor` is present it would be great! (even enabled by some feature)

**Comment by clouds56** [comment]
Image how this code would be like if using `ParseStream`, the compiler could warn me if cursor is not cloned
```rust
if let Ok((k, cursor_next)) = Comment::parse(cursor.clone(), ctx) {
    v.push(Child::C(k));
    cursor = cursor_next;
} else if let Ok((k, cursor_next)) = TemplateInner::parse(cursor.clone(), ctx) {
    v.push(Child::T(k));
    cursor = cursor_next;
} else if let Ok((k, cursor_next)) = Mustache::parse(cursor.clone(), ctx) {
    v.push(Child::M(k));
    cursor = cursor_next;
} else {
    error(cursor.span(), "not valid child")
}
```
But with `ParseStream` I would have to manually fork and advance it, the code is not readable in a large automata
```rust
let mut stream2 = stream.folk();
while let Ok(child) = Child::parse(stream, ctx) {
    v.push(child);
    stream2 = stream2.folk();
}
stream.advance_to(stream2);
```

**Comment by CAD97** [comment]
As I understand it, syn's parsing framework is deliberately biased to encourage LL(3) parsing, or in other words, parsing where you can tell which branch you're taking before you take the branch.

If you want to do a more PEG-like approach, this is supported by `parse::discouraged::Speculative`, but it's going to be less catered to. But the general shape for doing PEG with `Speculative` is

```rust
let fork = stream.fork();
if let Ok(thing) = Thing::parse(&fork) {
    stream.advance_to(&fork);
    thing
} else {
    // other choices
}
```

In fact, though, an actual finite automaton would fit within LL(3), because a finite automaton is roughly equivalent to LL(1). At any decision point, the FA knows which state to transition to with only the data presented to it.

The PEG approach is roughly

```
- try to parse Comment
- if that failed, try to parse TemplateInner
- if that failed, try to parse Mustache
- if that failed, error
```

whereas the LL(n) or FA approach is roughly

```
- peek at the head of the stream
- if it is a `//`, parse a Comment
- else if it is a `<`, parse a TemplateInner
- else if it is a `{{`, parse a Mustache
- else error
```

and syn wants to encourage the latter approach both because it is easier to generate useful errors with and it has more predictable performance characteristics than more general parsing algorithms.

**Comment by clouds56** [comment]
Thanks for explain, it's a very interesting point and I accept the "peek" approach.
The example I give is exceptions that cannot fit in FA, since I may not control what's inside. (most of my code is like)
```rust
fn step(mut cursor: Cursor, state: State) -> Result<(Cursor, State)> {
  let (token, cursor_next) = cursor.token_tree().map_err(|_| eof(cursor))?;
  match (state, token) {
    (State::S0, TokenTree::Punct(t)) if t.as_char() == '<' =>
      Ok((cursor_next, State::S1(...))),
    // ...
    (State::OneCase, TokenTree::Ident(t)) if &t.to_string() == 'fn' =>
      unimplemented!("parse_cursor::<syn::ItemFn>(cursor_next)"),
    // ...
    _ => Err(error(cursor, token))
  }
}
```
I almost finished my code with cursor (since it only needs low level api) until I realize I'd like to parse `syn::ItemFn` in some cases.

It's not for speculative parsing, you know I don't like it otherwise I would not use FA, but it's for the title "Public bridge between low and high level parser APIs."
I still like to use `Cursor` in my project since it has all the information, It's **easy to get** (`TokenBuffer::begin()`), **cheap to clone** (actually when you manipulate `ParseStream`, it's also copied everywhere) and **immutable** (this is very important, when I switched to `ParseStream` just now, I bit by it).
Now I wrapped `ParseStream` and use it as `Cursor` while still vote for a `discouraged::parse_cursor`.
