### ISSUE TITLE
The trait `std::marker::Send` is not implemented for `syn::parse::Error`

### ISSUE THREAD

**Issue by chtotut** [dtolnay/syn#497]
I try to convert from `syn::parse::Error` to `failure::Error` and receive this error message: "the trait `std::marker::Send` is not implemented". Is there a way to convert from `syn::parse::Error` to `failure::Error`?

**Comment by dtolnay** [comment]
Within a procedural macro you should never do this because it loses the ability to emit the error to the compiler in a way that points to the correct range of input tokens like a native compiler error.

Outside of a procedural macro you don't have that ability to begin with so I would write `failure::err_msg(err.to_string())`.

**Comment by chtotut** [comment]
Thanks.
