### ISSUE TITLE
Provide macro to define custom punctuation, analogous to custom keywords

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#502]
For example a function-like macro may want to use `<=>` as punctuation. Parsing this as `Token![<]` `Token![=]` `Token![>]` would be incorrect because it does not enforce that the tokens are Joint.

**Comment by dtolnay** [comment]
@CAD97 [may be working on this.](https://www.reddit.com/r/rust/comments/9ghwuv/hey_rustaceans_got_an_easy_question_ask_here/e6i3ksh/?context=3)

**Comment by CAD97** [comment]
It won't be possible to use the exact same strategy as `CustomKeyword` uses today for both a `CustomKeyword` and `CustomPunctuation` at the same time, as the implementations of `Sealed` and `Token` overlap.

This will require either finding another approach or putting `token::Sealed` in `$crate::export` so that it can be implemented on a case-by-case basis.

**Comment by dtolnay** [comment]
Added in #620.
