### ISSUE TITLE
Support direct comparison of Ident names?

### ISSUE THREAD

**Issue by dhardy** [dtolnay/syn#541]
`Ident` supports `PartialEq<T>` where `T: AsRef<str>` but doesn't support `AsRef<str>` itself. It would be nice to be able to directly compare two identifiers.

(Yes, it may be surprising that I even want to do this. I have "handler" functions whose name and implementation are supplied by the user, but need to look this up to generate the correct type bound automatically. Yeah, here be "magic".)

**Comment by dtolnay** [comment]
You should already be able to directly compare idents.

```rust
extern crate proc_macro2;
use proc_macro2::Ident;

fn eq(a: Ident, b: Ident) -> bool {
    a == b
}
```

---

If you are referring to `proc_macro::Ident`, I believe the compiler folks wanted to avoid `Ident: PartialEq<Ident>` because it is unclear how this behaves regarding hygiene. You may have two idents which are textually the same but carry distinguishable hygiene context that makes them not the same identifier.

```rust
fn main() {
    let x = 1;

    macro m($x:ident) {
        are_these_equal(x, $x);
    }

    let x = 2;

    m!(x);
}
```

The feeling is that anyone reaching for ident == ident is doing something that cannot be done correctly subject to the existing design of Rust.

**Comment by dhardy** [comment]
Oh, thanks for the hint. Talk about misleading error messages though:
```
$ cargo check
   Compiling mygui-macros v0.1.0 (/home/dhardy/projects/gui/mygui/mygui-macros)
error[E0277]: the trait bound `proc_macro2::Ident: std::convert::AsRef<str>` is not satisfied
   --> mygui-macros/src/lib.rs:363:32
    |
363 |                 if f.sig.ident == handler {
    |                                ^^ the trait `std::convert::AsRef<str>` is not implemented for `proc_macro2::Ident`
    |
    = note: required because of the requirements on the impl of `std::convert::AsRef<str>` for `&proc_macro2::Ident`
    = note: required because of the requirements on the impl of `std::cmp::PartialEq<&proc_macro2::Ident>` for `proc_macro2::Ident`

error: aborting due to previous error
```
But `f.sig.ident == *handler` works fine.

---

Yes, I am not using the same function-resolution strategy that Rust uses. I don't see a way around that, other than excessive verbosity on the users part (which also gives the user more scope to use incompatible types and get confusing error messages).
