### ISSUE TITLE
syn::Error with several spans?

### ISSUE THREAD

**Issue by Dushistov** [dtolnay/syn#558]
I use `syn` from `build.rs`, not inside "plugins for macros", but potentially it may be useful for them.

I want reports error with two spans.
Like for example compiler does, when report borrow problem: "mut borrow here" and "immutable borrow there".

With `syntex` it was possible via `DiagnosticBuilder::span_note`, may be it is possible to add similar method to `syn::Error`?

**Comment by dtolnay** [comment]
It would be neat to have a comprehensive diagnostics API usable from build.rs. But I would prefer for this to be provided by a different crate.

**Comment by Dushistov** [comment]
@dtolnay 

> It would be neat to have a comprehensive diagnostics API usable from build.rs. But I would prefer for this to be provided by a different crate.

But how any crate except `syn` can do it?
I porting my project from syntex, ok if there are no analog of syntex_error I can write it by my self.

But convincing the user to rebuild "world" with `procmacro2_semver_exempt`  as mentioned in #406 would be hard. Also the interface of `Span` looks is not really user friendly. The line number and column is suitable for report problem to user, but not for extracting part of code.

For example if I want wrap `syn::Error` after `syn::parse_str` I want to use `syn::Error::span(&self) -> syn::Span` to extract portion of `&str`, so I need `Lines` iterator and so on thing to simple thing.
If in addition to line number / column number there is offset from begin for start/end.

**Comment by dtolnay** [comment]
> But how any crate except `syn` can do it?

Well the syntex_errors crate provides a diagnostics API (DiagnosticBuilder) and syntex_errors is not syn, so we have proof that a crate other than syn can do this.

I would like to see a crate for rendering diagnostics like syntex_errors, but not built around compiler data structures. A minimal implementation would take in a source file or source code string, along with one or more line/column/message/severity (error, warn, note, suggestion, help) and render a good-looking message similar to how rustc would.

**Comment by Dushistov** [comment]
> I would like to see a crate for rendering diagnostics like syntex_errors, but not built around compiler data > structures

But what is the point of this hypothetical **crate** if there is no data for it's usage?

Or may be I missed something, and it is possible to specialize functions like `syn::do_parse_str`,
so it would use user supplied `Span` / `SourceFile` and so on things, instead of `proc_macro2::Span`?

**Comment by dtolnay** [comment]
The data would come by passing in the line and column of the span where you want to show the diagnostic, along with the message, and the source code that was being parsed so that the library can display the right line (and context, such as previous and next line).

**Comment by Dushistov** [comment]
@dtolnay 

> The data would come by passing...

It is clear how to implement, the problem that there is no reason to do so until it is possible to get line and column.

Plus it is not clear how pass **multi-span** errors from `syn` to my code, 
mutable global variables ?

For example 

```Rust
impl syn::parse::Parse for  MyItem {
    fn parse(input: ParseStream) -> syn::Result<Self> {
       //I want report multi-span error from here 
    }
}
```

**Comment by dtolnay** [comment]
I am closing the issue because I don't plan to address any of this in Syn. As mentioned, I would like to see someone else develop a separate library for diagnostics with support for rendering diagnostics from build.rs.

<br>

> It is clear how to implement, the problem that there is no reason to do so until it is impossible to get position and context information from proc_macro2::Span

I believe this is an orthogonal topic to the current issue. The `Span` type is not provided by Syn, so if your code can't get a line and column number out of it, then neither can Syn.

<br>

> Plus it is not clear how pass multi-span errors from syn to my code

This would be entirely up to the diagnostics library that somebody else needs to write so it would be better not to design it here. There are many many ways this could work and the usage basically shouldn't need to be different whether the implementation is from Syn or from a different crate.

For example:

```rust
impl Parse for MyItem {
    fn parse(input: ParseStream) -> Result<Self> {
        let err = please_create_a_pretty_diagnostic()
            .and_here_is_the_error_it_should_show(span0, "message...")
            .lets_make_a_helpful_note_too(span1, "...");
        Err(err)
    }
}

match syn::parse_str::<MyItem>(source_code) {
    Ok(item) => ...,
    Err(err) => {
        please_emit_this_error_and_make_it_pretty(source_code, err);
    }
}
```

Maybe this is encoding the line/column/messages directly in the syn::Error and unpacking it later to render. Maybe it is accumulating information in a thread-local diagnostics record and only encoding an index in the syn::Error. With a bit of imagination I'm sure somebody could come up with a dozen different ways to write this library and make it easy to use.
