### ISSUE TITLE
JSON representation of the AST

### ISSUE THREAD

**Issue by RReverser** [dtolnay/syn#606]
I'd sometimes like to dump the Rust AST as JSON for further analysis using external tools.

Do you think it would be acceptable to add `derive(Serialize)` under a separate feature flag to this crate?

**Comment by dtolnay** [comment]
This is provided in https://github.com/taiki-e/serde-syn.

**Comment by RReverser** [comment]
Hmm.

1. That looks like a fork of `syn`? Doesn't inspire much confidence in keeping up-to-date with real `syn` long-term to be honest... So the question stands - any chance such support could be integrated?
2. From the first glance, it lacks at least the location information, which is important for analysis.

**Comment by dtolnay** [comment]
1. I would not currently accept serialization impls in this crate. The syntax tree is large and complicated and I don't want to take on responsibility for the precise serialized representation. The data structures that work best for manipulating a syntax tree from Rust code are not necessarily the same as the data structures that make for a nice serialized representation to work with across languages. I am okay with focusing on the former while someone else works with stakeholders to figure out the latter.

2. Please let the crate author know what it would take to support your use case, or fork their implementation to add location information, or write your own.

**Comment by RReverser** [comment]
For 1 - if it would be as simple as adding `derive(Serialize)` under a feature flag, I don't suppose you would have to actually maintain it?

Also, at least for my usecases, it's more important to have precise structure compatible with up-to-date `syn` than some completely arbitrary 3rd-party representation, even if it's more idiomatic in some other language.

Essentially I want the same as `derive(Debug)` already provides on these structures, but in a machine-readable (JSON) format, and so far it seems as simple as adding another `derive`...

**Comment by taiki-e** [comment]
@RReverser

> if it would be as simple as adding `derive(Serialize)` under a feature flag,

AFAIK, it is not enough to do that for `syn`.

1. The type used in the fields of `syn`'s structures such as `Ident`, `TokenStream`, `Span`, etc... is the one defined in `proc_macro2` crate.

2. [The internal structure of `proc_macro2`'s structure is very different depending on whether `use_proc_macro` flag is valid](https://github.com/alexcrichton/proc-macro2/blob/0.4.27/src/lib.rs#L104-L108). Therefore, it needs to manually implement `Serialize` / `Deserialize` in the many `proc_macro2`'s structures.

**Comment by RReverser** [comment]
@taiki-e I see, thanks for explanations...

For me, the primary usecase right now is to add Rust support to https://astexplorer.net/ - a while ago, I implemented support for non-JavaScript languages there so that plugin developers could inspect AST of any parser and even experiment with transforms directly in the centralised playground.

By now various volunteers added support for different languages, but Rust is still missing. I thought it would be great to add it too, so that proc-macro developers could play with `syn` AST, inspect what different code corresponds to, and so on to ease development (just like it's currently done for other languages).

For this to work, I need a faithful, up-to-date JSON representation of `syn` AST suitable for parsing from ASTExplorer code and mapping locations between code and the typed structures.

Hence, fork is not ideal, as it can easily get out of sync, and stop being useful for purpose of seeing `syn` structures.

I guess I can use it for now as a start, but would rather love to find some way to resolve the issues you mentioned and have a guaranteed up-to-date JSON support in `syn` itself.

**Comment by dtolnay** [comment]
@RReverser Thanks for sharing more about your primary use case. That use case has totally different design constraints than most other uses of serializing Syn syntax trees to JSON, so I suspect you'll be on your own for making it work. I don't want to simply put Serde derives on all our types because that would kill any chance that somebody would pursue a more idiomatic JSON representation that works well across a variety of languages -- whereas you specifically want the Serde derives because your use case demands leaking Rust-specific details of the Rust representation of the syntax tree into the serialized JSON representation.

I would recommend building what you need on top of [syn.json](https://github.com/dtolnay/syn/blob/0.15.29/syn.json) which is a complete description of our syntax tree intended to support code generators including the one that generates Syn's own Fold / Visit / VisitMut traits. You would need to write a code generator that consumes syn.json and emits Serialize impls.

I am closing this issue because the approach I am recommending to you no longer requires the proposed feature.

**Comment by RReverser** [comment]
@dtolnay Oh, that's actually not a bad option. What are the stability guarantees for `syn.json` - is it going to be always in repo and in the same format? If so, that works well enough for my usecase and, indeed, I could go from there with my own codegen.

**Comment by dtolnay** [comment]
Currently none. I filed #607 to follow up and would be willing to consider PRs related to that.

**Comment by RReverser** [comment]
Thanks, that should work :)
