### ISSUE TITLE
Resolve path

### ISSUE THREAD

**Issue by tage64** [dtolnay/syn#612]
Hi!
This may not be possible at all, but I wonder if it is possible to resolve a path. Let's say I have a syn::Path which points to a trait. I would like to get the source code for the implementation of the trait. Or at least a list of all methods in the trait. Is that possible?

Best regards,
Tage

**Comment by dtolnay** [comment]
This information does not exist in the compiler during macro expansion. In part because the trait itself may come from a macro that hasn't run yet. Or a macro that hasn't run yet may change what that path refers to by adding an import. The compiler fully expands all macros before doing any name resolution.
