### ISSUE TITLE
Failable ident constructor

### ISSUE THREAD

**Issue by derekdreery** [dtolnay/syn#623]
I have a string, and need to check it is a valid identifier, but if I try to use Ident::new on an invalid string it panics. Instead, it could

 1. provide a `Ident::try_new` or similar returning a `Result`
 2. modify the signature of `Ident::new` to return a `Result`

what do people think?

**Comment by hcpl** [comment]
Since `proc-macro2` tries to mirror the `rustc`-provided `proc-macro` public API and `proc_macro::Ident::new` has been stabilized [for a while now](https://doc.rust-lang.org/src/proc_macro/lib.rs.html#809-812) its signature won't be modified in either place.

As for the first suggestion, I think it could be brought up in [rust/rust-lang](https://github.com/rust/rust-lang) first so that `proc-macro2` could follow up on this.

In the meantime you can either have an identifier check in your code like [what `proc-macro2` does](https://docs.rs/proc-macro2/0.4.27/src/proc_macro2/fallback.rs.html#569-596) or rely on a [`std::panic::catch_unwind`](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) hack in this way:

```rust
let ident_ok = panic::catch_unwind(|| Ident::new("foo", Span::call_site()));
let ident_err = panic::catch_unwind(|| Ident::new("%", Span::call_site()));
```

**Comment by dtolnay** [comment]
`syn::parse_str::<Ident>` is our fallible constructor:

```rust
println!("{:?}", syn::parse_str::<Ident>("foo"));
println!("{:?}", syn::parse_str::<Ident>("%"));
```

**Comment by dtolnay** [comment]
I've added a brief explanation and link to syn::parse_str from the documentation of Ident::new.
