### ISSUE TITLE
Rename macro input to derive input?

### ISSUE THREAD

**Issue by SimonSapin** [dtolnay/syn#63]
`syn` has a `parse_macro_input` function and a `MacroInput` type. Despite their name, they are very specific to implementing a custom `derive`.

Macros 1.1 will presumably support macros like `foo!()`, and `syn` will be useful for implementing those too. (Maybe with something like `Vec<TokenTree>` to represent the input.)

Should `parse_macro_input` and `MacroInput` be renamed to `parse_derive_input` and `DeriveInput`? Or maybe `parse_type_definiton` and `TypeDefinition`?

**Comment by liigo** [comment]
+1, you said what I want to say.

**Comment by dtolnay** [comment]
+1 for DeriveInput. I'll take care of this in the next breaking release.

Speaking of `foo!()`, I've been working on a separate library to help with those! :smiling_imp:

**Comment by SimonSapin** [comment]
@dtolnay Cool! Is that library online yet? Why should it be separate from syn?

**Comment by dtolnay** [comment]
Not online yet. It certainly leverages syn to provide easy handling of snippets that are valid Rust syntax but the concept allows it to be a lot more flexible than what syn can do. It covers the full spectrum from "the argument to my macro is basically a Rust expression" through "the argument to my macro is this wacky DSL that I dreamed up and tried implementing in macro_rules but gave up 5000 lines in."

It should be separate from syn because I don't want to hyperinflate syn version numbers due to experimenting with that new piece. I would be more comfortable merging it into syn after the concept has solidified some more.

**Comment by dtolnay** [comment]
I made this change in 0e837400be98ca95f6085e52a18a0124a52f46c9.

**Comment by dtolnay** [comment]
And released in [0.11.0](https://github.com/dtolnay/syn/releases/tag/0.11.0).
