### ISSUE TITLE
Make syn interoperable with proc_quote

### ISSUE THREAD

**Issue by Robbepop** [dtolnay/syn#635]
As far as I found out `syn` is partly incompatible with `proc_quote`.
For example `syn`s `parse_quote` still uses goo'old `quote` while your crate is mainly using `proc_quote` for quasi quoting.
A `syn` crate feature `proc_quote` could probably be sufficient to add the interoperability.
Also this issue might be resolved then: https://github.com/dtolnay/syn/issues/545

How likely is it to completely drop `quote` and go full-in on `proc_quote` for the next major release of `syn`?

**Comment by dtolnay** [comment]
The next version of quote will have a `quote = { features = ["proc"] }` flag that is based on proc macro. I am taking a different approach than proc-quote to improve on the compile time significantly, of both the crate and the code it generates -- so that a downstream crate like serde_derive ends up compiling as fast or faster including dependencies vs plain quote. I don't plan to support proc-quote but I think this makes your problem go away. In the meantime they would be free to expose a different parse_quote macro.

This is not relevant to #545.
