### ISSUE TITLE
What's the suggested way to parse an entire crate, not just a single file?

### ISSUE THREAD

**Issue by shepmaster** [dtolnay/syn#68]
Right now, the parsing accepts a `&str` and as far as I can see, it wouldn't know how to find other files. Is this too far out of scope?

**Comment by dtolnay** [comment]
Libsyntax inlines modules by default and I have found it to be super unhelpful, and have to work around it every time. People perpetually think of new ways to screw it up, for example:

```rust
#[cfg_attr(not(feature = "why"), path = "a.rs")]
#[cfg_attr(feature = "why", path = "b.rs")]
mod m;
```

From my perspective, it seems like resolving modules like this is the job of the Rust compiler when you go to compile your crate, so it is out of scope for syn. I could be convinced otherwise if you come up with a good API for it.

In your case (if this is still for finding unsafe blocks) you may be better off using [`walkdir`](https://github.com/BurntSushi/walkdir) to parse each *.rs file individually.
