### ISSUE TITLE
Why have a kind of Field in spite of that Fields has two variants Named and Unnamed?

### ISSUE THREAD

**Issue by megumish** [dtolnay/syn#698]
I think it more reasonable that there are Named Field and UnnamedField because it's strange that Fields have two variants and when it is extracted as each Field whose ident have that is extra two variants as Option type.

Thanks.

**Comment by dtolnay** [comment]
A lot of code that looks at Field benefits from dealing with named fields and tuple fields uniformly, such as code that only needs the attrs or types of the fields. If you have fields that you know are named (because they came from FieldsNamed) then you can unwrap the Option\<Ident\> to get the names.

**Comment by megumish** [comment]
I understand that its implement benefits others. Thank you for the reply.
