### ISSUE TITLE
Errors when updating from 1.0.5 to 1.06

### ISSUE THREAD

**Issue by leudz** [dtolnay/syn#713]
Hi, cargo just updated syn to "1.0.6" and now I have 4 errors in [a crate](https://github.com/leudz/shipyard/tree/master) I haven't touched in more than a month. I tried "1.0.5" and no error.

I have 3 times the same error followed by a different one:
> the trait bound `syn::ty::Type: std::convert::From<proc_macro2::TokenStream>` is not satisfied

> the trait bound `syn::pat::Pat: std::convert::From<proc_macro2::TokenStream>` is not satisfied

**Comment by dtolnay** [comment]
Sorry about the breakage! Those impls were added unintentionally and I didn't expect anyone to be using them. They have confusing behavior that is almost never what you want because they can end up putting tokens that are not a valid type into a syn::Type. I sent a fix in https://github.com/leudz/shipyard/pull/19 along with some other improvements to make up for the trouble.

**Comment by leudz** [comment]
Oh, there's no problem, I just noticed it and was like "hmm that's weird". The macro worked, it was enough for me but with accurate span and error handling instead of panic it looks much better. You really didn't have to do all this 😄
Many thanks!
