### ISSUE TITLE
FunctionRetTy does not implement to_tokens

### ISSUE THREAD

**Issue by gnzlbg** [dtolnay/syn#80]
It's an enum around Nothing or Ty, and the docs say that when it is Nothing the return type is not specified and defaults to `()`. 

Since Ty implements `to_tokens`, and the tokens of nothing are just `()`, why doesn't it implement `to_tokens` ?

**Comment by dtolnay** [comment]
I would be open to adding an impl. It is tricky because both closures, function declarations, and function types all use FunctionRetTy and there is a difference in the meaning of Default between closures and functions.

What would you expect to get printed? Nothing in the case of FunctionRetTy::Default, and `"-> $ty"` in the case of FunctionRetTy::Ty?

**Comment by gnzlbg** [comment]
> What would you expect to get printed? Nothing in the case of FunctionRetTy::Default, and "-> $ty" in the case of FunctionRetTy::Ty?

I think there are two options:

- A: print `-> $ty` and nothing, users write `fn () #FunctionRetTyValue`,
- B: print `$ty` and `()`, users write `fn () -> #FunctionRetTyValue`. 

I am leaning more for the second one since it sounds more flexible, but any of both would make my life easier. Right now when generating functions I need two quotes, one for the case the function has a return type, and one for the case in which it does not.

**Comment by dtolnay** [comment]
I don't like B because it does the wrong thing in the case of a closure.

```rust
quote! {
    |a, b, c| -> #ret { f(c, b, a) }
}
```

Your code might work most of the time but eventually someone will give you `FunctionRetTy::Default` and now it's broken.

Note that if you ever want to replace an impl from syn or add a new one, here is one way to do it. This way you can avoid having separate `quote!` calls for the two cases and you can customize the behavior to be what makes sense for your crate.

```rust
struct MyQuote<T>(T);

impl ToTokens for MyQuote<FunctionRetTy> {
    fn to_tokens(&self, tokens: &mut Tokens) {
        match self.0 {
            FunctionRetTy::Default => tokens.append("()"),
            FunctionRetTy::Ty(ref ty) => ty.to_tokens(tokens),
        }
    }
}

let ret = /* some FunctionRetTy */;
let ret = MyQuote(ret);
quote! {
    fn () -> #ret
}
```

**Comment by gnzlbg** [comment]
@dtolnay Thanks!

**Comment by dtolnay** [comment]
I think the least confusing approach is to keep this unimplemented and have users write the 10 lines of code to say what they mean.
