### ISSUE TITLE
Release 0.10.7 breaks semver compatibility

### ISSUE THREAD

**Issue by RReverser** [dtolnay/syn#84]
Copying comment from https://github.com/dtolnay/syn/issues/66:

> @dtolnay Looks like you released it in 0.10.7 because @SimonSapin bumped version as part of his commit https://github.com/dtolnay/syn/commit/07c7341b0a0a4b5801f6957d168f36b70905e3e0 and thus broke semver - our build started failing with ``Use of undeclared type or module `BlockCheckMode` `` when Cargo started auto-pulling 0.10.7 instead of 0.10.6 :(

Maybe it's worth to unpublish release from Cargo? (I'm pretty sure we're not the only one whose build was broken)

**Comment by SimonSapin** [comment]
Ah, this is my mistake. I branched my PR #83 from 881a5ef "Merge tag 0.10.6 into master", but I should have used 66a31d6 (tag: 0.10.6) "Release 0.10.6" instead. The former probably includes breaking changes from another branch.

I think 0.10.7 should be yanked from crates.io. @dtolnay, I’d appreciate if you could also make 0.10.8 with the unicode-xid upgrade from the correct base. I can provide a PR if you’d like, but since it’s a small change it might be easier to do it yourself?

**Comment by SimonSapin** [comment]
@RReverser In the meantime, I think `cargo update -p syn --precise 0.10.6` should fix your build.

**Comment by RReverser** [comment]
@SimonSapin Not on Travis (unless we commit `Cargo.lock` too which is likely not what we want to do at the moment; alternatively could add this command to `.travis.yml` but then it seems better and more reliable to just yank this version).

**Comment by SimonSapin** [comment]
Yes, this version should be yanked. This was just an attempt to unblock you until dtolnay can get around to doing it.

**Comment by RReverser** [comment]
@SimonSapin Yeah, appreciate that.

**Comment by dtolnay** [comment]
I yanked 0.10.7 and published 0.10.8 for @SimonSapin based on the correct commit. Really sorry about the break here.

**Comment by RReverser** [comment]
@dtolnay All good, thanks for the fast turnaround!
