### ISSUE TITLE
Is it possible to take impl information for a struct in proc macro (derive)?

### ISSUE THREAD

**Issue by vityafx** [dtolnay/syn#94]
I wonder is there such a possiblity to iterate through a list of methods of a structure in custom derive? I was not able to find anything for this in `syn` documentation.

**Comment by oli-obk** [comment]
This is not possible, since the `#[derive(...)]` has only access to the code that is directly in the `enum TypeName { ... }` or `struct TypeName { ... }` after the attribute. Methods are defined in their own `impl TypeName { ... }` item.

**Comment by vityafx** [comment]
@oli-obk Yes, it seems to me so too. But maybe there is some another way to take `impl` part?

**Comment by oli-obk** [comment]
Not with anything that works through `derive` on a stable compiler.

**Comment by vityafx** [comment]
@oli-obk what about nightly one?

**Comment by oli-obk** [comment]
you can write your own compiler plugin, but I can tell you from personal experience, that accessing impl blocks from code generating plugins is hard and often impossible.

The problem is, that the impl blocks might also contain macros/attributes that expand some code, and that might happen before your plugin or after it, there's no guarantee.

Maybe we can help you solve your problem in another way? What's your actual problem that you want to solve? (not accessing impl methods, but why do you want to access impl methods)

**Comment by vityafx** [comment]
I just want to make objects of one class have a list of methods at runtime...
